# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='classis_course',
            field=models.CharField(default='', max_length=50, verbose_name='经典课程'),
        ),
    ]
