# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-28 11:04
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_classis_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='文章内容'),
        ),
    ]
