# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-28 11:47
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20171228_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teacher/%Y%m', verbose_name='头像')),
                ('index', models.IntegerField(default=1, verbose_name='序号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构图片',
                'verbose_name_plural': '机构图片',
            },
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='机构详情'),
        ),
        migrations.AddField(
            model_name='orgimage',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
